package microtest.domain.model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "actor")
public class Actor implements Serializable {

    @Column(name = "first_name", table = "actor", nullable = false, length = 45)
    @Basic
    private String firstName;

    @Column(name = "last_name", table = "actor", nullable = false, length = 45)
    @Basic
    private String lastName;

    @OneToMany(targetEntity = FilmActor.class, mappedBy = "actor")
    private List<FilmActor> filmActorCollection;

    @Column(name = "actor_id", table = "actor", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long actorId;

    @Column(name = "last_update", table = "actor", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date lastUpdate;

    public Actor() {

    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public List<FilmActor> getFilmActorCollection() {
        return this.filmActorCollection;
    }

    public void setFilmActorCollection(List<FilmActor> filmActorCollection) {
        this.filmActorCollection = filmActorCollection;
    }

    public Long getActorId() {
        return this.actorId;
    }

    public void setActorId(Long actorId) {
        this.actorId = actorId;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}
