package microtest.domain.model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "address")
public class Address implements Serializable {

    @OneToMany(targetEntity = Store.class, mappedBy = "addressId")
    private List<Store> storeCollection;

    @Column(name = "address", table = "address", nullable = false, length = 50)
    @Basic
    private String address;

    @Column(name = "address2", table = "address", length = 50)
    @Basic
    private String address2;

    @Column(name = "phone", table = "address", nullable = false, length = 20)
    @Basic
    private String phone;

    @OneToMany(targetEntity = Customer.class, mappedBy = "addressId")
    private List<Customer> customerCollection;

    @Column(name = "district", table = "address", nullable = false, length = 20)
    @Basic
    private String district;

    @Column(name = "postal_code", table = "address", length = 10)
    @Basic
    private String postalCode;

    @Column(name = "last_update", table = "address", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date lastUpdate;

    @Column(name = "location", table = "address", nullable = false)
    @Lob
    @Basic
    private byte[] location;

    @OneToMany(targetEntity = Staff.class, mappedBy = "addressId")
    private List<Staff> staffCollection;

    @ManyToOne(optional = false, targetEntity = City.class)
    @JoinColumn(name = "city_id")
    private City cityId;

    @Column(name = "address_id", table = "address", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long addressId;

    public Address() {

    }

    public List<Store> getStoreCollection() {
        return this.storeCollection;
    }

    public void setStoreCollection(List<Store> storeCollection) {
        this.storeCollection = storeCollection;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getAddress2() {
        return this.address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public List<Customer> getCustomerCollection() {
        return this.customerCollection;
    }

    public void setCustomerCollection(List<Customer> customerCollection) {
        this.customerCollection = customerCollection;
    }

    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getPostalCode() {
        return this.postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public byte[] getLocation() {
        return this.location;
    }

    public void setLocation(byte[] location) {
        this.location = location;
    }

    public List<Staff> getStaffCollection() {
        return this.staffCollection;
    }

    public void setStaffCollection(List<Staff> staffCollection) {
        this.staffCollection = staffCollection;
    }

    public City getCityId() {
        return this.cityId;
    }

    public void setCityId(City cityId) {
        this.cityId = cityId;
    }

    public Long getAddressId() {
        return this.addressId;
    }

    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }
}
