package microtest.domain.model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.security.access.annotation.Secured;

@Entity
@Table(name = "city")
public class City implements Serializable {

    @OneToMany(targetEntity = Address.class, mappedBy = "cityId")
    private List<Address> addressCollection;

    @Column(name = "city", table = "city", nullable = false, length = 50)
    @Basic
    private String city;

    @Column(name = "last_update", table = "city", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date lastUpdate;

    @Column(name = "city_id", table = "city", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long cityId;

    @ManyToOne(optional = false, targetEntity = Country.class)
    @JoinColumn(name = "country_id")
    private Country countryId;

    public City() {

    }

    public List<Address> getAddressCollection() {
        return this.addressCollection;
    }

    public void setAddressCollection(List<Address> addressCollection) {
        this.addressCollection = addressCollection;
    }
    @Secured("ROLE_ADMIN")
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public Long getCityId() {
        return this.cityId;
    }

    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    public Country getCountryId() {
        return this.countryId;
    }

    public void setCountryId(Country countryId) {
        this.countryId = countryId;
    }
}
