package microtest.domain.model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;

public class FilmActorPK implements Serializable {

    private Long actorId;

    private Long filmId;

    public FilmActorPK() {

    }

    public Long getActorId() {
        return this.actorId;
    }

    public void setActorId(Long actorId) {
        this.actorId = actorId;
    }

    public Long getFilmId() {
        return this.filmId;
    }

    public void setFilmId(Long filmId) {
        this.filmId = filmId;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 59 * hash + this.actorId.intValue();
        hash = 59 * hash + this.filmId.intValue();
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final FilmActorPK other = (FilmActorPK) obj;
        if (this.actorId != other.actorId) {
            return false;
        }
        if (this.filmId != other.filmId) {
            return false;
        }
        return true;
    }

}
