package microtest.domain.model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

@Entity
@Table(name = "film_text")
public class FilmText implements Serializable {

    @Column(name = "film_id", table = "film_text", nullable = false)
    @Id
    private Short filmId;

    @Column(name = "description", table = "film_text", length = 65535)
    @Lob
    @Basic
    private String description;

    @Column(name = "title", table = "film_text", nullable = false)
    @Basic
    private String title;

    public FilmText() {

    }

    public Short getFilmId() {
        return this.filmId;
    }

    public void setFilmId(Short filmId) {
        this.filmId = filmId;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
}
