package microtest.domain.model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "inventory")
public class Inventory implements Serializable {

    @OneToMany(targetEntity = Rental.class, mappedBy = "inventoryId")
    private List<Rental> rentalCollection;

    @Column(name = "last_update", table = "inventory", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date lastUpdate;

    @ManyToOne(optional = false, targetEntity = Film.class)
    @JoinColumn(name = "film_id")
    private Film filmId;

    @Column(name = "inventory_id", table = "inventory", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long inventoryId;

    @ManyToOne(optional = false, targetEntity = Store.class)
    @JoinColumn(name = "store_id")
    private Store storeId;

    public Inventory() {

    }

    public List<Rental> getRentalCollection() {
        return this.rentalCollection;
    }

    public void setRentalCollection(List<Rental> rentalCollection) {
        this.rentalCollection = rentalCollection;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public Film getFilmId() {
        return this.filmId;
    }

    public void setFilmId(Film filmId) {
        this.filmId = filmId;
    }

    public Long getInventoryId() {
        return this.inventoryId;
    }

    public void setInventoryId(Long inventoryId) {
        this.inventoryId = inventoryId;
    }

    public Store getStoreId() {
        return this.storeId;
    }

    public void setStoreId(Store storeId) {
        this.storeId = storeId;
    }
}
