package microtest.domain.model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "language")
public class Language implements Serializable {

    @Column(name = "last_update", table = "language", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date lastUpdate;

    @OneToMany(targetEntity = Film.class, mappedBy = "languageId")
    private List<Film> filmCollection;

    @Column(name = "language_id", table = "language", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long languageId;

    @Column(name = "name", table = "language", nullable = false, length = 20)
    @Basic
    private String name;

    @OneToMany(targetEntity = Film.class, mappedBy = "originalLanguageId")
    private List<Film> filmCollection1;

    public Language() {

    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public List<Film> getFilmCollection() {
        return this.filmCollection;
    }

    public void setFilmCollection(List<Film> filmCollection) {
        this.filmCollection = filmCollection;
    }

    public Long getLanguageId() {
        return this.languageId;
    }

    public void setLanguageId(Long languageId) {
        this.languageId = languageId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Film> getFilmCollection1() {
        return this.filmCollection1;
    }

    public void setFilmCollection1(List<Film> filmCollection1) {
        this.filmCollection1 = filmCollection1;
    }
}
