package microtest.domain.model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "rental", uniqueConstraints = @UniqueConstraint(columnNames = {"rental_date", "inventory_id", "customer_id"}))
public class Rental implements Serializable {

    @Column(name = "rental_date", table = "rental", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date rentalDate;

    @Column(name = "return_date", table = "rental")
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date returnDate;

    @Column(name = "last_update", table = "rental", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date lastUpdate;

    @ManyToOne(optional = false, targetEntity = Customer.class)
    @JoinColumn(name = "customer_id")
    private Customer customerId;

    @ManyToOne(optional = false, targetEntity = Inventory.class)
    @JoinColumn(name = "inventory_id")
    private Inventory inventoryId;

    @OneToMany(targetEntity = Payment.class, mappedBy = "rentalId")
    private List<Payment> paymentCollection;

    @ManyToOne(optional = false, targetEntity = Staff.class)
    @JoinColumn(name = "staff_id")
    private Staff staffId;

    @Column(name = "rental_id", table = "rental", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long rentalId;

    public Rental() {

    }

    public Date getRentalDate() {
        return this.rentalDate;
    }

    public void setRentalDate(Date rentalDate) {
        this.rentalDate = rentalDate;
    }

    public Date getReturnDate() {
        return this.returnDate;
    }

    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public Customer getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Customer customerId) {
        this.customerId = customerId;
    }

    public Inventory getInventoryId() {
        return this.inventoryId;
    }

    public void setInventoryId(Inventory inventoryId) {
        this.inventoryId = inventoryId;
    }

    public List<Payment> getPaymentCollection() {
        return this.paymentCollection;
    }

    public void setPaymentCollection(List<Payment> paymentCollection) {
        this.paymentCollection = paymentCollection;
    }

    public Staff getStaffId() {
        return this.staffId;
    }

    public void setStaffId(Staff staffId) {
        this.staffId = staffId;
    }

    public Long getRentalId() {
        return this.rentalId;
    }

    public void setRentalId(Long rentalId) {
        this.rentalId = rentalId;
    }
}
