package microtest.domain.model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "staff")
public class Staff implements Serializable {

    @Column(name = "last_name", table = "staff", nullable = false, length = 45)
    @Basic
    private String lastName;

    @OneToMany(targetEntity = Rental.class, mappedBy = "staffId")
    private List<Rental> rentalCollection;

    @Column(name = "active", table = "staff", nullable = false)
    @Basic
    private boolean active;

//    @OneToOne(targetEntity = Store.class)
//    private Store store;

    @ManyToOne(optional = false, targetEntity = Store.class)
    @JoinColumn(name = "store_id")
    private Store storeId;

    @OneToMany(targetEntity = Payment.class, mappedBy = "staffId")
    private List<Payment> paymentCollection;

    @Column(name = "picture", table = "staff")
    @Lob
    @Basic
    private byte[] picture;

    @ManyToOne(optional = false, targetEntity = Address.class)
    @JoinColumn(name = "address_id")
    private Address addressId;

    @Column(name = "first_name", table = "staff", nullable = false, length = 45)
    @Basic
    private String firstName;

    @Column(name = "password", table = "staff", length = 40)
    @Basic
    private String password;

    @Column(name = "last_update", table = "staff", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date lastUpdate;

    @Column(name = "staff_id", table = "staff", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long staffId;

    @Column(name = "email", table = "staff", length = 50)
    @Basic
    private String email;

    @Column(name = "username", table = "staff", nullable = false, length = 16)
    @Basic
    private String username;

    public Staff() {

    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public List<Rental> getRentalCollection() {
        return this.rentalCollection;
    }

    public void setRentalCollection(List<Rental> rentalCollection) {
        this.rentalCollection = rentalCollection;
    }

    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }


    public Store getStoreId() {
        return this.storeId;
    }

    public void setStoreId(Store storeId) {
        this.storeId = storeId;
    }

    public List<Payment> getPaymentCollection() {
        return this.paymentCollection;
    }

    public void setPaymentCollection(List<Payment> paymentCollection) {
        this.paymentCollection = paymentCollection;
    }

    public byte[] getPicture() {
        return this.picture;
    }

    public void setPicture(byte[] picture) {
        this.picture = picture;
    }

    public Address getAddressId() {
        return this.addressId;
    }

    public void setAddressId(Address addressId) {
        this.addressId = addressId;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public Long getStaffId() {
        return this.staffId;
    }

    public void setStaffId(Long staffId) {
        this.staffId = staffId;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}
